version: '3'
services:
 #Nodejs
  my-community-backend:
    build: .
    image: iths/my-community-backend
    container_name: my-community-backend
    working_dir: /app
    volumes:
       - ./:/app
    command: bash -c "yarn install; yarn run dev"
    env_file: 
      - ./.env.docker
    ports:
        - "3009:8080"