# serverless.yml

service: my-community-serverless

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-north-1
  memorySize: 512
  timeout: 30
  httpApi:
    cors: true

plugins:
  - serverless-dotenv-plugin
  - serverless-vpc-discovery
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3009
    lambdaPort: 3004
  dotenv:
    path: ".env.docker"
    required:
      file: true
  vpc:
    vpcName: "my-lambda-vpc"
    subnetNames:
      - "1"
      - "2"
      - "3"
    securityGroupNames:
      - "my-lambda"

functions:
  getAll:
    handler: build/controllers/user.create
    events:
      - http:
          path: 'api/user'
          method: POST

  testPost:
    handler: build/handler.testTypeScript
    events:
      - http:
          path: 'api/test'
          method: post