# serverless.yml

service: my-community-serverless

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-north-1
  memorySize: 512
  timeout: 30
  httpApi:
    cors: true

plugins:
  - serverless-dotenv-plugin
  - serverless-vpc-discovery
  - serverless-offline


custom:
  serverless-offline:
    httpPort: 3009
    lambdaPort: 3004
  dotenv:
    path: ".env.docker"
    required:
      file: true
  vpc:
    vpcName: "my-lambda-vpc"
    subnetNames:
      - "1"
      - "2"
      - "3"
    securityGroupNames:
      - "my-lambda"
  custom:
    middleware:
      folderName: '.middleware' # defaults to '.middleware'
      cleanFolder: true        # defaults to 'true'

functions:
  userCreate:
    handler: build/controllers/user.routeCreate
    events:
      - http:
          path: 'api/user'
          method: POST

  userLogin:
    handler: build/controllers/user.routeLogin
    events:
      - http:
          path: 'api/user/login'
          method: POST
  userInfo:
    handler: build/controllers/user.routeUserInfo
    events:
      - http:
          path: 'api/user/info'
          method: GET
  userUpdate:
    handler: build/controllers/user.routeUserUpdate
    events:
      - http:
          path: 'api/users/{userId}'
          method: 'PUT'
  userDelete:
    handler: build/controllers/user.routeUserUpdate
    events:
      - http:
          path: 'api/users/{userId}'
          method: 'DELETE'
  userFindAll:
    handler: build/controllers/user.routeFindAll
    events:
      - http:
          path: 'api/users'
          method: GET
  userFind:
    handler: build/controllers/user.routeFind
    events:
      - http:
          path: 'api/users/{username}'
          method: GET
  
  postCreate:
    handler: build/controllers/post.routeCreate
    events:
       - http:
           path: api/post
           method: POST
  postDelete:
    handler: build/controllers/post.routeDelete
    events:
       - http:
           path: api/post/{postId}
           method: DELETE
  postUser:
    handler: build/controllers/post.routeUserPosts
    events:
      - http:
          path: api/user/posts
          method: GET
  
  followCreate:
    handler: build/controllers/follow.routeFollow
    events:
      - http:
         path: api/follow/{targetUserId}
         method: POST
  followDelete:
    handler: build/controllers/follow.routeUnFollow
    events:
      - http:
          path: api/follow/{targetUserId}
          method: DELETE